name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm i
        working-directory: ./examples
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            ./examples/node_modules

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present lint
      - run: npm run --if-present dep-check
      - run: npm run --if-present docs:no-publish
      - run: npm run --if-present doc-check
  test-node:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [lts/*]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:node
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: node
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:chrome
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: chrome
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-chrome-webworker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:chrome-webworker
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: chrome-webworker
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:firefox
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: firefox
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-firefox-webworker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npm run --if-present test:firefox-webworker
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: firefox-webworker
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-webkit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npx playwright install-deps
      - run: npm run --if-present test:webkit
      - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
        with:
          flags: webkit
          files: .coverage/*,packages/*/.coverage/*
          token: ${{ secrets.CODECOV_TOKEN }}

  test-examples:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
        with:
          directories: |
            ./examples/node_modules
      - uses: actions/setup-go@v5
      - run: go build -o test-runner main.go
        working-directory: ./examples/test-runner
      - run: ../test-runner/test-runner -hasProxy
        working-directory: ./examples/go-libp2p-http-proxy
      - run: ../test-runner/test-runner
        working-directory: ./examples/js-libp2p-client-and-node-server/
      - run: ../test-runner/test-runner
        working-directory: ./examples/two-js-peers
      - run: ./runTests.sh
        working-directory: ./examples/peer-id-auth
